[project]
name = "pers-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "tqdm>=4.67.2",
]

[dependency-groups]
dev = [
    "pgcli>=4.4.0",
]
